import type { BusinessLineCode } from "../analytics/kpi-registry.ts";

export type ManagedBranchRecord = {
  id: string;
  countryIso2: "SV" | "HN";
  businessLineCode: Exclude<BusinessLineCode, "CONSOLIDATED">;
  branchName: string;
  branchManagerName: string;
  areaManagerName: string;
  areaZone: string;
  isActive: boolean;
  sourceTrace: string;
  demoFlag: true;
};

export const managedBranchRecords: ManagedBranchRecord[] = [
  {
    id: "managed-sv-laboratory-ss-escalon-l001",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Escalon - L001",
    branchManagerName: "Vanessa Guillén",
    areaManagerName: "Obed Alexander Alas Montoya",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-merliot-l003",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Merliot - L003",
    branchManagerName: "MARVIN ROMERO",
    areaManagerName: "Obed Alexander Alas Montoya",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-plaza-soma-l007",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Plaza Soma - L007",
    branchManagerName: "Daniel Córdova",
    areaManagerName: "Obed Alexander Alas Montoya",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-santa-elena-l005",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Santa Elena - L005",
    branchManagerName: "Abigail Arredondo",
    areaManagerName: "Obed Alexander Alas Montoya",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-casco-l010",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Casco - L010",
    branchManagerName: "Kriscia Dominguez",
    areaManagerName: "Obed Alexander Alas Montoya",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-escalon-2",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS- Escalón 2",
    branchManagerName: "Lesly Aguilar",
    areaManagerName: "Obed Alexander Alas Montoya",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-contac-center-laboratorio",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "Contac Center Laboratorio",
    branchManagerName: "Ashley Candelario",
    areaManagerName: "Obed Alexander Alas Montoya",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-la-libertad-l031",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - La Libertad-L031",
    branchManagerName: "Damaris Lopez",
    areaManagerName: "Ana Maria Rivera Monroy",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-merliot-2-l039",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS-Merliot 2 - L039",
    branchManagerName: "Devy Campos",
    areaManagerName: "Ana Maria Rivera Monroy",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-plaza-sur-l018",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Plaza Sur - L018",
    branchManagerName: "Judith Melgar",
    areaManagerName: "Ana Maria Rivera Monroy",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-santa-tecla-l011",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Santa Tecla - L011",
    branchManagerName: "Melvin Cerna",
    areaManagerName: "Ana Maria Rivera Monroy",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-chalatenango-l036",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS-Chalatenango - L036",
    branchManagerName: "Ulises Mayen",
    areaManagerName: "Ana Maria Rivera Monroy",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-aguilares",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS-Aguilares",
    branchManagerName: "Katherine Leonardo",
    areaManagerName: "Ana Maria Rivera Monroy",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-constitucion-l009",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Constitucion - L009",
    branchManagerName: "Doménica López",
    areaManagerName: "Ana Maria Rivera Monroy",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-el-trebol-l046",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS-El Trebol-L046",
    branchManagerName: "Claudia Rivera",
    areaManagerName: "Ana Maria Rivera Monroy",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-sta-ana-santa-ana-1-l008",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "Sta Ana - Santa Ana 1 - L008",
    branchManagerName: "Tania Alarcón",
    areaManagerName: "Andrea Alejandra Cassio Cortez",
    areaZone: "Occidente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-sta-ana-santa-ana-2-l013",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "Sta Ana - Santa Ana 2 - L013",
    branchManagerName: "Felipe Duran",
    areaManagerName: "Andrea Alejandra Cassio Cortez",
    areaZone: "Occidente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-sta-ana-ramblas-santa-ana-l032",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "Sta Ana -Ramblas Santa Ana- L032",
    branchManagerName: "Doris Gómez",
    areaManagerName: "Andrea Alejandra Cassio Cortez",
    areaZone: "Occidente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-sta-ana-metapan-l014",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "Sta Ana - Metapan - L014",
    branchManagerName: "Zoila Orantes",
    areaManagerName: "Andrea Alejandra Cassio Cortez",
    areaZone: "Occidente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-sta-ana-ahuachapan-l044",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "Sta Ana - Ahuachapán-L044",
    branchManagerName: "Tatiana Morales",
    areaManagerName: "Andrea Alejandra Cassio Cortez",
    areaZone: "Occidente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-sta-ana-sonsonate-1-l006",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "Sta Ana - Sonsonate 1 - L006",
    branchManagerName: "Greisy Aguirre",
    areaManagerName: "Andrea Elena Rivera Hernandez",
    areaZone: "Sonsonate",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-lourdes-l012",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Lourdes - L012",
    branchManagerName: "María José Morán",
    areaManagerName: "Andrea Elena Rivera Hernandez",
    areaZone: "Sonsonate",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-opico-l019",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Opico - L019",
    branchManagerName: "Angélica Frías",
    areaManagerName: "Andrea Elena Rivera Hernandez",
    areaZone: "Sonsonate",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-marsella-l040",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS-Marsella-L040",
    branchManagerName: "Josue Paniagua",
    areaManagerName: "Andrea Elena Rivera Hernandez",
    areaZone: "Sonsonate",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-sta-ana-sonsonate-2-l020",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "Sta Ana - Sonsonate 2 - L020",
    branchManagerName: "Yoselin Martinez",
    areaManagerName: "Andrea Elena Rivera Hernandez",
    areaZone: "Sonsonate",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-analiza-sta-ana-sonsonate-3-l041",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "Analiza Sta Ana - Sonsonate 3 - L041",
    branchManagerName: "Yenni Cortez",
    areaManagerName: "Andrea Elena Rivera Hernandez",
    areaZone: "Sonsonate",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-cara-sucia-l043",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS- Cara Sucia-L043",
    branchManagerName: "Krisscia Garcia",
    areaManagerName: "Andrea Elena Rivera Hernandez",
    areaZone: "Sonsonate",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-medica-1-l002",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Medica 1 - L002",
    branchManagerName: "Joselyn Servellón",
    areaManagerName: "Karen Lissette Rodriguez Aguilar",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-medica-2-l004",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Medica 2 - L004",
    branchManagerName: "Merari Ramírez",
    areaManagerName: "Karen Lissette Rodriguez Aguilar",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-medica-3-l025",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Medica 3 - L025",
    branchManagerName: "María Elena Alvarenga",
    areaManagerName: "Karen Lissette Rodriguez Aguilar",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-medica-4-l029",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Medica 4 - L029",
    branchManagerName: "David Aguirre",
    areaManagerName: "Karen Lissette Rodriguez Aguilar",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-soyapango-l023",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Soyapango - L023",
    branchManagerName: "Liliana Gómez",
    areaManagerName: "Karen Lissette Rodriguez Aguilar",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-san-martin-l015",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - San Martin- L015",
    branchManagerName: "Nancy Castro",
    areaManagerName: "Karen Lissette Rodriguez Aguilar",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-paseo-venecia-l026",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - Paseo Venecia - L026",
    branchManagerName: "Silvia Cerón",
    areaManagerName: "Karen Lissette Rodriguez Aguilar",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-san-gabriel-l017",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS - San Gabriel - L017",
    branchManagerName: "Emerson Quintanilla",
    areaManagerName: "Karen Lissette Rodriguez Aguilar",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-valle-dulce-l028",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS- Valle Dulce -L028",
    branchManagerName: "Tania Pineda",
    areaManagerName: "Karen Lissette Rodriguez Aguilar",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-ss-cojutepeque-l030",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "SS- Cojutepeque - L030",
    branchManagerName: "Jacqueline Diaz",
    areaManagerName: "Karen Lissette Rodriguez Aguilar",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-san-miguel-san-miguel-1-l016",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "San Miguel - San Miguel 1 - L016",
    branchManagerName: "Brenda Platero",
    areaManagerName: "José William Ramos Chicas.",
    areaZone: "Oriente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-san-miguel-san-miguel-2-l021",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "San Miguel - San Miguel 2 - L021",
    branchManagerName: "Johanna Alvarez",
    areaManagerName: "José William Ramos Chicas.",
    areaZone: "Oriente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-san-miguel-san-miguel-3-l027",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "San Miguel - San Miguel 3 - L027",
    branchManagerName: "Irving Rodriguez",
    areaManagerName: "José William Ramos Chicas.",
    areaZone: "Oriente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-san-miguel-usulutan-l022",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "San Miguel - Usulutan - L022",
    branchManagerName: "Nelly Ramos",
    areaManagerName: "José William Ramos Chicas.",
    areaZone: "Oriente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-san-miguel-zacatecoluca-l037",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "San Miguel- Zacatecoluca - L037",
    branchManagerName: "Camila Recinos",
    areaManagerName: "José William Ramos Chicas.",
    areaZone: "Oriente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-laboratory-san-miguel-usulutan-2-l042",
    countryIso2: "SV",
    businessLineCode: "LABORATORY",
    branchName: "San Miguel-Usulutan 2- L042",
    branchManagerName: "Gabriela Torres",
    areaManagerName: "José William Ramos Chicas.",
    areaZone: "Oriente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-physiotherapy-ss-santa-elena-fisioterapia",
    countryIso2: "SV",
    businessLineCode: "PHYSIOTHERAPY",
    branchName: "SS - Santa Elena Fisioterapia",
    branchManagerName: "Abigail Arredondo",
    areaManagerName: "Edwin Isaac Santillana",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-physiotherapy-ss-medica-3-fisioterapia",
    countryIso2: "SV",
    businessLineCode: "PHYSIOTHERAPY",
    branchName: "SS - Medica 3 Fisioterapia",
    branchManagerName: "María Elena Alvarenga",
    areaManagerName: "Edwin Isaac Santillana",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-physiotherapy-sta-ana-santa-ana-2-fisioterapia",
    countryIso2: "SV",
    businessLineCode: "PHYSIOTHERAPY",
    branchName: "Sta Ana - Santa Ana 2 Fisioterapia",
    branchManagerName: "Andrea Rivera",
    areaManagerName: "Edwin Isaac Santillana",
    areaZone: "Occidente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-physiotherapy-ss-centro-medico-l024",
    countryIso2: "SV",
    businessLineCode: "PHYSIOTHERAPY",
    branchName: "SS - Centro Medico - L024",
    branchManagerName: "Kriscia Dominguez",
    areaManagerName: "Edwin Isaac Santillana",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-physiotherapy-ss-escalon-fisioterapia",
    countryIso2: "SV",
    businessLineCode: "PHYSIOTHERAPY",
    branchName: "SS-Escalón Fisioterapia",
    branchManagerName: "Doris Duran",
    areaManagerName: "Edwin Isaac Santillana",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-physiotherapy-ss-soma-fisioterapia",
    countryIso2: "SV",
    businessLineCode: "PHYSIOTHERAPY",
    branchName: "SS-Soma Fisioterapia",
    branchManagerName: "Amanda Vasquez",
    areaManagerName: "Edwin Isaac Santillana",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-imaging-imagenes-valle-dulce",
    countryIso2: "SV",
    businessLineCode: "IMAGING",
    branchName: "Imágenes Valle Dulce",
    branchManagerName: "Tania Pineda",
    areaManagerName: "Elsy Stefany Silva",
    areaZone: "Sonsonate",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-imaging-imagenes-medica",
    countryIso2: "SV",
    businessLineCode: "IMAGING",
    branchName: "Imágenes Médica",
    branchManagerName: "Karla Andrea Contreras",
    areaManagerName: "Elsy Stefany Silva",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-imaging-imagenes-santa-ana",
    countryIso2: "SV",
    businessLineCode: "IMAGING",
    branchName: "Imágenes Santa Ana",
    branchManagerName: "Damaris Fuentes",
    areaManagerName: "Elsy Stefany Silva",
    areaZone: "Occidente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-imaging-imagenes-escalon",
    countryIso2: "SV",
    businessLineCode: "IMAGING",
    branchName: "Imágenes Escalón",
    branchManagerName: "Gabriela Alfaro",
    areaManagerName: "Elsy Stefany Silva",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-imaging-imagenes-escalon-2",
    countryIso2: "SV",
    businessLineCode: "IMAGING",
    branchName: "Imágenes Escalon 2",
    branchManagerName: "Lesly Aguilar",
    areaManagerName: "Elsy Stefany Silva",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-imaging-imagenes-sonsonate-3",
    countryIso2: "SV",
    businessLineCode: "IMAGING",
    branchName: "Imágenes Sonsonate 3",
    branchManagerName: "Yenni Cortez",
    areaManagerName: "Elsy Stefany Silva",
    areaZone: "Sonsonate",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-imaging-imagenes-la-union",
    countryIso2: "SV",
    businessLineCode: "IMAGING",
    branchName: "Imágenes La Unión",
    branchManagerName: "Maria Jose Alfaro",
    areaManagerName: "Elsy Stefany Silva",
    areaZone: "Oriente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-imaging-imagenes-zacatecoluca",
    countryIso2: "SV",
    businessLineCode: "IMAGING",
    branchName: "Imágenes Zacatecoluca",
    branchManagerName: "Camila Recinos",
    areaManagerName: "Elsy Stefany Silva",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-imaging-imagenes-ahuchapan",
    countryIso2: "SV",
    businessLineCode: "IMAGING",
    branchName: "Imágenes Ahuchapan",
    branchManagerName: "Tatiana Morales",
    areaManagerName: "Elsy Stefany Silva",
    areaZone: "Oriente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-imaging-imagenes-aguilares",
    countryIso2: "SV",
    businessLineCode: "IMAGING",
    branchName: "Imágenes Aguilares",
    branchManagerName: "Katherine Leonardo",
    areaManagerName: "Elsy Stefany Silva",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-sv-imaging-imagenes-usulutan-2",
    countryIso2: "SV",
    businessLineCode: "IMAGING",
    branchName: "Imágenes Usulután 2",
    branchManagerName: "Gabriela Torres",
    areaManagerName: "Elsy Stefany Silva",
    areaZone: "Oriente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-suc-ciudad-nueva",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Suc. Ciudad Nueva",
    branchManagerName: "Noelia Raudales",
    areaManagerName: "Karla Mendez",
    areaZone: "Centro Sur",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-suc-valencia",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Suc. Valencia",
    branchManagerName: "Alba Lourdes Martinez",
    areaManagerName: "Karla Mendez",
    areaZone: "Centro Sur",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-suc-aeroplaza",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Suc. Aeroplaza",
    branchManagerName: "Maryuri Gisell Varela",
    areaManagerName: "Karla Mendez",
    areaZone: "Centro Sur",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-suc-city-plaza",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Suc. City Plaza",
    branchManagerName: "No hay",
    areaManagerName: "Karla Mendez",
    areaZone: "Centro Sur",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-suc-loarque",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Suc. Loarque",
    branchManagerName: "Jenny Gabriela Velasquez",
    areaManagerName: "Karla Mendez",
    areaZone: "Centro Sur",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-suc-tres-caminos",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Suc.Tres Caminos",
    branchManagerName: "Angela Azucena Carbajal",
    areaManagerName: "Karla Mendez",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-imaging-suc-tres-caminos",
    countryIso2: "HN",
    businessLineCode: "IMAGING",
    branchName: "Suc.Tres Caminos",
    branchManagerName: "No hay",
    areaManagerName: "Karla Mendez",
    areaZone: "Centro",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-suc-danli",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Suc. Danli",
    branchManagerName: "Cecia Paola Cubas",
    areaManagerName: "Karla Mendez",
    areaZone: "Oriente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-suc-el-paraiso",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Suc. El Paraiso",
    branchManagerName: "No hay",
    areaManagerName: "Karla Mendez",
    areaZone: "Oriente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-suc-zamorano",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Suc. Zamorano",
    branchManagerName: "No hay",
    areaManagerName: "Karla Mendez",
    areaZone: "Oriente",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-boulevard-del-norte",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Boulevard del Norte",
    branchManagerName: "Blanca Ester Alvarez",
    areaManagerName: "Melissa Canales",
    areaZone: "Zona Norte",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-calpules",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Calpules",
    branchManagerName: "Karen Yariela Aguilar",
    areaManagerName: "Melissa Canales",
    areaZone: "Zona Norte",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-catarino",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Catarino",
    branchManagerName: "Daira de la Cruz Garcia",
    areaManagerName: "Melissa Canales",
    areaZone: "Zona Norte",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-leonardo",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Leonardo",
    branchManagerName: "No hay",
    areaManagerName: "Melissa Canales",
    areaZone: "Zona Norte",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-choloma",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Choloma",
    branchManagerName: "Alejandra Ferrufino",
    areaManagerName: "Melissa Canales",
    areaZone: "Zona Norte",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-lopez-arellano",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Lopez Arellano",
    branchManagerName: "Delmy Cristina Garcia",
    areaManagerName: "Melissa Canales",
    areaZone: "Zona Norte",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-call-center",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Call Center",
    branchManagerName: "Oscar Matute",
    areaManagerName: "Melissa Canales",
    areaZone: "Zona Norte",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-hospital-escuela",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Hospital Escuela",
    branchManagerName: "Jimmy Vladimir Dohm",
    areaManagerName: "Lesby Diaz",
    areaZone: "Tegucigalpa",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-boulevard-morazan",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Boulevard Morazán",
    branchManagerName: "Stephanie Raquel Ayala",
    areaManagerName: "Lesby Diaz",
    areaZone: "Tegucigalpa",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-kennedy",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Kennedy",
    branchManagerName: "Mario Alexi Gomez",
    areaManagerName: "Lesby Diaz",
    areaZone: "Tegucigalpa",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-choluteca-blvar-mauricio-oliva",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Choluteca - Blvar Mauricio Oliva",
    branchManagerName: "Rixi Paola Espinal",
    areaManagerName: "Lesby Diaz",
    areaZone: "Choluteca",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-san-lorenzo",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "San Lorenzo",
    branchManagerName: "Kelyn Marisol Espinal",
    areaManagerName: "Lesby Diaz",
    areaZone: "San Lorenzo",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-choluteca-hospital-del-sur",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Choluteca Hospital del Sur",
    branchManagerName: "Gabriela Castello",
    areaManagerName: "Lesby Diaz",
    areaZone: "Choluteca",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-la-granja",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "La Granja",
    branchManagerName: "Fernando Ordoñez",
    areaManagerName: "Lesby Diaz",
    areaZone: "Tegucigalpa",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-san-marcos-de-colon",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "San Marcos De Colon",
    branchManagerName: "No hay",
    areaManagerName: "Lesby Diaz",
    areaZone: "Choluteca",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-comayaguela",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Comayaguela",
    branchManagerName: "No hay",
    areaManagerName: "Lesby Diaz",
    areaZone: "Tegucigalpa",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-comayagua-hospital-santa-teresa",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Comayagua - Hospital Santa Teresa",
    branchManagerName: "No hay",
    areaManagerName: "Stephany Figueroa",
    areaZone: "Comayagua",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-comayagua-bvl-roberto-larios",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Comayagua - Bvl Roberto Larios",
    branchManagerName: "Karla Lara",
    areaManagerName: "Stephany Figueroa",
    areaZone: "Comayagua",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-centro",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Centro",
    branchManagerName: "Issel Gomez",
    areaManagerName: "Stephany Figueroa",
    areaZone: "Tegucigalpa",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-plaza-tracoma",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Plaza Tracoma",
    branchManagerName: "No hay",
    areaManagerName: "Stephany Figueroa",
    areaZone: "Tegucigalpa",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-san-miguel",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "San Miguel",
    branchManagerName: "Maria Jose Garcia",
    areaManagerName: "Stephany Figueroa",
    areaZone: "Tegucigalpa",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-sante-fe",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Sante Fe",
    branchManagerName: "Eritson Oseguera",
    areaManagerName: "Stephany Figueroa",
    areaZone: "Tegucigalpa",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-hato-de-en-medio",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Hato de en medio",
    branchManagerName: "Estefany Lopez",
    areaManagerName: "Stephany Figueroa",
    areaZone: "Tegucigalpa",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-laboratory-plaza-nova",
    countryIso2: "HN",
    businessLineCode: "LABORATORY",
    branchName: "Plaza Nova",
    branchManagerName: "No hay",
    areaManagerName: "Stephany Figueroa",
    areaZone: "Tegucigalpa",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: true,
    demoFlag: true,
  },
  {
    id: "managed-hn-physiotherapy-aun-no-activo",
    countryIso2: "HN",
    businessLineCode: "PHYSIOTHERAPY",
    branchName: "Aun no Activo",
    branchManagerName: "No hay",
    areaManagerName: "Francisco Matamoros",
    areaZone: "Tegucigalpa",
    sourceTrace: "DEMO ddddd2.xlsx / info general",
    isActive: false,
    demoFlag: true,
  },
];
